# Generated by Django 5.0.1 on 2024-02-03 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Records",
            new_name="Record",
        ),
    ]
