# Generated by Django 5.0.1 on 2024-02-03 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0002_rename_records_record"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images"),
        ),
    ]
